import { DAY, HOUR, MINUTE, RateLimiter } from "@convex-dev/rate-limiter";
import { components } from "../_generated/api";

export const rateLimiter = new RateLimiter(components.rateLimiter, {
  aiGenerationPerOrg: {
    capacity: 60,
    kind: "token bucket",
    period: DAY,
    rate: 300,
  },
  aiGenerationPerUser: {
    capacity: 20,
    kind: "token bucket",
    period: HOUR,
    rate: 60,
  },
  anonymousFeedbackPerOrg: {
    capacity: 20,
    kind: "token bucket",
    period: HOUR,
    rate: 60,
  },
  authEmailSendGlobal: {
    capacity: 2000,
    kind: "token bucket",
    period: HOUR,
    rate: 2000,
  },
  authPasswordResetPerEmail: {
    capacity: 3,
    kind: "token bucket",
    period: HOUR,
    rate: 3,
  },
  authSignInPerEmail: {
    capacity: 10,
    kind: "token bucket",
    period: 15 * MINUTE,
    rate: 10,
  },
  authSignUpPerEmail: {
    capacity: 5,
    kind: "token bucket",
    period: HOUR,
    rate: 5,
  },
  authVerificationEmailPerEmail: {
    capacity: 3,
    kind: "token bucket",
    period: HOUR,
    rate: 3,
  },
  competitorScrapePerOrg: {
    capacity: 10,
    kind: "token bucket",
    period: DAY,
    rate: 20,
  },
  emailSubscriptionPerOrg: {
    capacity: 20,
    kind: "token bucket",
    period: HOUR,
    rate: 60,
  },
  feedbackInteractionPerUser: {
    capacity: 30,
    kind: "token bucket",
    period: MINUTE,
    rate: 30,
  },
  feedbackPerUser: {
    capacity: 20,
    kind: "token bucket",
    period: HOUR,
    rate: 60,
  },
  intelligenceScanPerOrg: {
    capacity: 3,
    kind: "token bucket",
    period: DAY,
    rate: 5,
  },
  invitationEmailPerOrg: {
    capacity: 20,
    kind: "token bucket",
    period: DAY,
    rate: 50,
  },
  invitationEmailPerUser: {
    capacity: 20,
    kind: "token bucket",
    period: DAY,
    rate: 50,
  },
  platformTriageFailureAlert: {
    capacity: 1,
    kind: "token bucket",
    period: HOUR,
    rate: 1,
  },
  publicApiScreenshotUploadPerPublicKey: {
    capacity: 300,
    kind: "token bucket",
    period: MINUTE,
    rate: 300,
  },
  publicApiSurveyAnswerPerPublicKey: {
    capacity: 3000,
    kind: "token bucket",
    period: MINUTE,
    rate: 3000,
  },
  publicApiSurveyStartPerPublicKey: {
    capacity: 600,
    kind: "token bucket",
    period: MINUTE,
    rate: 600,
  },
  publicApiWritePerPublicKey: {
    capacity: 30,
    kind: "token bucket",
    period: MINUTE,
    rate: 30,
  },
  publicApiWritePerSecretKey: {
    capacity: 300,
    kind: "token bucket",
    period: MINUTE,
    rate: 300,
  },
  storageUploadPerUser: {
    capacity: 30,
    kind: "token bucket",
    period: HOUR,
    rate: 120,
  },
  subscriptionConfirmationPerEmail: {
    capacity: 3,
    kind: "token bucket",
    period: DAY,
    rate: 5,
  },
  supportContactConfirmationPerEmail: {
    capacity: 3,
    kind: "token bucket",
    period: DAY,
    rate: 3,
  },
  supportContactConfirmationPerRecipient: {
    capacity: 5,
    kind: "token bucket",
    period: DAY,
    rate: 5,
  },
  supportConversationPerGuestEmail: {
    capacity: 5,
    kind: "token bucket",
    period: HOUR,
    rate: 10,
  },
  supportConversationPerOrg: {
    capacity: 100,
    kind: "token bucket",
    period: HOUR,
    rate: 300,
  },
  supportCustomerMessagePerConversation: {
    capacity: 20,
    kind: "token bucket",
    period: HOUR,
    rate: 60,
  },
  supportDomainEmailPerOrg: {
    capacity: 1000,
    kind: "token bucket",
    period: DAY,
    rate: 5000,
  },
  supportForwardingTestPerOrg: {
    capacity: 5,
    kind: "token bucket",
    period: HOUR,
    rate: 10,
  },
  supportInboundNewConversationPerOrg: {
    capacity: 100,
    kind: "token bucket",
    period: DAY,
    rate: 500,
  },
  supportInboundNewConversationPerSender: {
    capacity: 5,
    kind: "token bucket",
    period: HOUR,
    rate: 10,
  },
  supportInboundPerConversation: {
    capacity: 10,
    kind: "token bucket",
    period: HOUR,
    rate: 30,
  },
  supportInboxAlertPerMember: {
    capacity: 20,
    kind: "token bucket",
    period: DAY,
    rate: 50,
  },
  supportNoticePerOrg: {
    capacity: 100,
    kind: "token bucket",
    period: DAY,
    rate: 500,
  },
  supportNoticePerRecipient: {
    capacity: 10,
    kind: "token bucket",
    period: DAY,
    rate: 20,
  },
  supportOutboundConversationPerOrg: {
    capacity: 50,
    kind: "token bucket",
    period: DAY,
    rate: 200,
  },
  surveyLinkAnswerPerResponse: {
    capacity: 60,
    kind: "token bucket",
    period: MINUTE,
    rate: 60,
  },
  surveyLinkCompletePerResponse: {
    capacity: 5,
    kind: "token bucket",
    period: MINUTE,
    rate: 5,
  },
  surveyLinkStartPerRespondent: {
    capacity: 10,
    kind: "token bucket",
    period: MINUTE,
    rate: 10,
  },
  surveyLinkStartPerSurvey: {
    capacity: 600,
    kind: "token bucket",
    period: MINUTE,
    rate: 600,
  },
  unsignedExternalUserPerOrg: {
    capacity: 500,
    kind: "token bucket",
    period: HOUR,
    rate: 1500,
  },
  widgetConversationPerVisitor: {
    capacity: 5,
    kind: "token bucket",
    period: HOUR,
    rate: 10,
  },
  widgetConversationPerWidget: {
    capacity: 100,
    kind: "token bucket",
    period: HOUR,
    rate: 300,
  },
  widgetEmailChangePerConversation: {
    capacity: 5,
    kind: "token bucket",
    period: HOUR,
    rate: 5,
  },
  widgetMessagePerVisitor: {
    capacity: 10,
    kind: "token bucket",
    period: MINUTE,
    rate: 30,
  },
  widgetMessagePerWidget: {
    capacity: 200,
    kind: "token bucket",
    period: HOUR,
    rate: 2000,
  },
});
