import {
  Brain,
  Chat,
  ChatCircle,
  Code,
  CreditCard,
  FileText,
  Gear,
  GithubLogo,
  Palette,
  User,
  Users,
} from "@phosphor-icons/react";
import type { CommandItem } from "./types";

export const commandItems: CommandItem[] = [
  // Navigation
  {
    id: "feedback",
    label: "Feedback",
    keywords: ["feedback", "posts", "ideas", "suggestions", "bugs"],
    group: "navigation",
    href: "/dashboard/$orgSlug",
    icon: Chat,
    description: "View and manage feedback",
    requiresOrg: true,
  },
  {
    id: "changelog",
    label: "Changelog",
    keywords: ["changelog", "releases", "updates", "announcements"],
    group: "navigation",
    href: "/dashboard/$orgSlug/changelog",
    icon: FileText,
    description: "Manage changelog entries",
    requiresOrg: true,
    requiresAdmin: true,
  },
  {
    id: "inbox",
    label: "Inbox",
    keywords: ["inbox", "messages", "support", "chat"],
    group: "navigation",
    href: "/dashboard/$orgSlug/inbox",
    icon: ChatCircle,
    description: "View support conversations",
    requiresOrg: true,
    requiresAdmin: true,
  },
  {
    id: "widgets",
    label: "Widgets",
    keywords: ["widgets", "embed", "code", "integration"],
    group: "navigation",
    href: "/dashboard/$orgSlug/widgets",
    icon: Code,
    description: "Configure embedded widgets",
    requiresOrg: true,
    requiresAdmin: true,
  },
  {
    id: "ai",
    label: "AI",
    keywords: ["ai", "artificial intelligence", "assistant"],
    group: "navigation",
    href: "/dashboard/$orgSlug/ai",
    icon: Brain,
    description: "AI assistant settings",
    requiresOrg: true,
    requiresAdmin: true,
  },

  // Settings
  {
    id: "settings",
    label: "Settings",
    keywords: ["settings", "configuration", "preferences"],
    group: "settings",
    href: "/dashboard/$orgSlug/settings",
    icon: Gear,
    description: "Organization settings",
    requiresOrg: true,
  },
  {
    id: "settings-general",
    label: "General Settings",
    keywords: ["general", "name", "organization"],
    group: "settings",
    href: "/dashboard/$orgSlug/settings/general",
    icon: Gear,
    description: "General organization settings",
    requiresOrg: true,
    requiresAdmin: true,
  },
  {
    id: "settings-branding",
    label: "Branding",
    keywords: ["branding", "logo", "colors", "theme", "appearance"],
    group: "settings",
    href: "/dashboard/$orgSlug/settings/branding",
    icon: Palette,
    description: "Customize appearance",
    requiresOrg: true,
    requiresAdmin: true,
  },
  {
    id: "settings-members",
    label: "Members",
    keywords: ["members", "team", "users", "invite", "people"],
    group: "settings",
    href: "/dashboard/$orgSlug/settings/members",
    icon: Users,
    description: "Manage team members",
    requiresOrg: true,
    requiresAdmin: true,
  },
  {
    id: "settings-github",
    label: "GitHub",
    keywords: ["github", "git", "repository", "sync"],
    group: "settings",
    href: "/dashboard/$orgSlug/settings/github",
    icon: GithubLogo,
    description: "GitHub integration",
    requiresOrg: true,
    requiresAdmin: true,
  },
  {
    id: "settings-billing",
    label: "Billing",
    keywords: ["billing", "payment", "subscription", "plan", "stripe"],
    group: "settings",
    href: "/dashboard/$orgSlug/settings/billing",
    icon: CreditCard,
    description: "Manage billing and subscription",
    requiresOrg: true,
    requiresAdmin: true,
  },

  // Actions
  {
    id: "account",
    label: "Account",
    keywords: ["account", "profile", "personal"],
    group: "actions",
    href: "/dashboard/account",
    icon: User,
    description: "Your personal account",
  },
];

export const groupLabels: Record<string, string> = {
  navigation: "Pages",
  settings: "Settings",
  actions: "Actions",
};
