import {
  Chat,
  ChatCircle,
  Code,
  Cube,
  FileText,
  Heartbeat,
  User,
} from "@phosphor-icons/react";
import type { CommandItem } from "./types";

export const commandItems: CommandItem[] = [
  // Navigation
  {
    id: "feedback",
    label: "Feedback",
    keywords: ["feedback", "posts", "ideas", "suggestions", "bugs"],
    group: "navigation",
    href: "/dashboard/$orgSlug",
    icon: Chat,
    description: "View and manage feedback",
    requiresOrg: true,
  },
  {
    id: "changelog",
    label: "Changelog",
    keywords: ["changelog", "releases", "updates", "announcements"],
    group: "navigation",
    href: "/dashboard/$orgSlug/changelog",
    icon: FileText,
    description: "Manage changelog entries",
    requiresOrg: true,
    requiresAdmin: true,
  },
  {
    id: "inbox",
    label: "Inbox",
    keywords: ["inbox", "messages", "support", "chat"],
    group: "navigation",
    href: "/dashboard/$orgSlug/inbox",
    icon: ChatCircle,
    description: "View support conversations",
    requiresOrg: true,
    requiresAdmin: true,
  },
  {
    id: "in-app",
    label: "In-App",
    keywords: ["in-app", "widgets", "embed", "code", "integration"],
    group: "navigation",
    href: "/dashboard/$orgSlug/in-app",
    icon: Code,
    description: "Configure in-app integrations",
    requiresOrg: true,
    requiresAdmin: true,
  },
  {
    id: "status",
    label: "Status",
    keywords: ["status", "uptime", "monitors", "health", "incidents", "outage"],
    group: "navigation",
    href: "/dashboard/$orgSlug/status",
    icon: Heartbeat,
    description: "Monitor service health and incidents",
    requiresOrg: true,
    requiresAdmin: true,
  },
  {
    id: "project",
    label: "Project",
    keywords: [
      "project",
      "settings",
      "configuration",
      "github",
      "branding",
      "members",
      "billing",
      "ai",
      "intelligence",
      "changelog",
      "releases",
      "mcp",
    ],
    group: "navigation",
    href: "/dashboard/$orgSlug/project",
    icon: Cube,
    description: "Project settings and configuration",
    requiresOrg: true,
    requiresAdmin: true,
  },

  // Actions
  {
    id: "account",
    label: "Account",
    keywords: ["account", "profile", "personal"],
    group: "actions",
    href: "/dashboard/account",
    icon: User,
    description: "Your personal account",
  },
];

export const groupLabels: Record<string, string> = {
  navigation: "Pages",
  actions: "Actions",
};
