/**
 * Built-in coding adapter using AI SDK v6 + GitHub API.
 *
 * This is the default adapter that works out of the box.
 * GitHub API helpers are in ./builtin_github.ts.
 */

import {
  BUILTIN_REF_REGEX,
  buildHeaders,
  createBranch,
  createPullRequest,
  getCIStatus,
  listDirectoryFromGitHub,
  parseRepoUrl,
  readFileFromGitHub,
  searchCodeInRepo,
} from "./builtin_github";
import type {
  ActivityLogEntry,
  CodingAdapter,
  CodingTaskInput,
  CodingTaskOutput,
  TaskStatusResponse,
} from "./types";

const GITHUB_API = "https://api.github.com";

const log = (
  agent: ActivityLogEntry["agent"],
  level: ActivityLogEntry["level"],
  message: string,
  details?: string
): ActivityLogEntry => ({
  agent,
  level,
  message,
  details,
  timestamp: Date.now(),
});

export const builtinAdapter: CodingAdapter = {
  name: "builtin",
  displayName: "Built-in (AI SDK + GitHub API)",
  requiredCredentials: ["githubToken"],

  executeTask: async (
    input: CodingTaskInput,
    credentials: Record<string, string>
  ): Promise<CodingTaskOutput> => {
    const { githubToken } = credentials;
    const logs: ActivityLogEntry[] = [];
    let tokensUsed = 0;
    const estimatedCostUsd = 0;

    try {
      const { owner, repo } = parseRepoUrl(input.repoUrl);
      logs.push(log("dev", "info", `Parsed repo: ${owner}/${repo}`));

      // Step 1: Create feature branch
      logs.push(log("dev", "action", `Creating branch ${input.featureBranch}`));
      await createBranch(
        owner,
        repo,
        input.featureBranch,
        input.baseBranch,
        githubToken
      );
      logs.push(log("dev", "success", "Branch created"));

      // Step 2: Explore codebase to understand context
      logs.push(log("dev", "action", "Exploring codebase structure..."));
      const rootFiles = await listDirectoryFromGitHub(
        owner,
        repo,
        "",
        input.baseBranch,
        githubToken
      );
      logs.push(
        log(
          "dev",
          "info",
          `Found ${rootFiles.length} files/dirs at root`,
          rootFiles.map((f) => f.name).join(", ")
        )
      );

      // Step 3: Read AGENTS.md if present
      const agentsMd = await readFileFromGitHub(
        owner,
        repo,
        "AGENTS.md",
        input.baseBranch,
        githubToken
      );
      if (agentsMd) {
        logs.push(
          log("dev", "info", "Found AGENTS.md — will follow coding rules")
        );
      }

      // Step 4: Search for relevant code based on the task
      logs.push(log("dev", "action", "Searching for relevant code..."));
      const searchResults = await searchCodeInRepo(
        owner,
        repo,
        input.title,
        githubToken
      );
      logs.push(
        log(
          "dev",
          "info",
          `Found ${searchResults.length} relevant code locations`,
          searchResults.map((r) => r.path).join(", ")
        )
      );

      // Step 5: For the MVP, we create the PR with the technical spec
      // as the body. The actual code generation will be done by the
      // AI SDK agent loop in a future iteration with Vercel Sandbox.
      //
      // This placeholder creates a draft PR with the spec so the
      // human or a more capable agent can pick it up.
      logs.push(
        log("dev", "action", "Creating draft PR with technical spec...")
      );

      const prBody = [
        "## Autopilot Task",
        "",
        `**Agent:** Dev (${builtinAdapter.displayName})`,
        "**Priority:** Based on task queue",
        "",
        "## Technical Spec",
        "",
        input.technicalSpec,
        "",
        "## Acceptance Criteria",
        "",
        ...input.acceptanceCriteria.map((c) => `- [ ] ${c}`),
        "",
        "---",
        "*Generated by Reflet Autopilot*",
      ].join("\n");

      const { prUrl, prNumber } = await createPullRequest(
        owner,
        repo,
        `[autopilot] ${input.title}`,
        prBody,
        input.featureBranch,
        input.baseBranch,
        githubToken
      );

      logs.push(log("dev", "success", `Draft PR created: #${prNumber}`, prUrl));
      tokensUsed = 0; // No LLM calls in GitHub-API-only mode

      return {
        status: "success",
        prUrl,
        prNumber,
        branch: input.featureBranch,
        activityLogs: logs,
        tokensUsed,
        estimatedCostUsd,
        externalRef: `builtin:${owner}/${repo}#${prNumber}`,
      };
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      logs.push(log("dev", "error", `Task failed: ${errorMessage}`));
      return {
        status: "failed",
        activityLogs: logs,
        tokensUsed,
        estimatedCostUsd,
        errorMessage,
      };
    }
  },

  getStatus: async (
    externalRef: string,
    credentials: Record<string, string>
  ): Promise<TaskStatusResponse> => {
    const { githubToken } = credentials;

    // Parse externalRef: "builtin:owner/repo#prNumber"
    const match = externalRef.match(BUILTIN_REF_REGEX);
    if (!match?.groups) {
      return {
        status: "failed",
        activityLogs: [],
        tokensUsed: 0,
        estimatedCostUsd: 0,
      };
    }

    const { owner, repo, pr } = match.groups;

    // Check PR status
    const prResponse = await fetch(
      `${GITHUB_API}/repos/${owner}/${repo}/pulls/${pr}`,
      { headers: buildHeaders(githubToken) }
    );

    if (!prResponse.ok) {
      return {
        status: "failed",
        activityLogs: [],
        tokensUsed: 0,
        estimatedCostUsd: 0,
      };
    }

    const prData = (await prResponse.json()) as {
      state: string;
      merged: boolean;
      head: { ref: string };
      html_url: string;
      number: number;
    };

    if (prData.merged) {
      return {
        status: "completed",
        prUrl: prData.html_url,
        prNumber: prData.number,
        ciStatus: "passed",
        activityLogs: [],
        tokensUsed: 0,
        estimatedCostUsd: 0,
      };
    }

    // Check CI
    const ci = await getCIStatus(owner, repo, prData.head.ref, githubToken);

    return {
      status: ci.status === "failed" ? "failed" : "running",
      prUrl: prData.html_url,
      prNumber: prData.number,
      ciStatus: ci.status,
      ciFailureLog: ci.failureLog,
      activityLogs: [],
      tokensUsed: 0,
      estimatedCostUsd: 0,
    };
  },

  cancelTask: async (
    externalRef: string,
    credentials: Record<string, string>
  ): Promise<void> => {
    const match = externalRef.match(BUILTIN_REF_REGEX);
    if (!match?.groups) {
      return; // Can't parse ref — nothing to cancel
    }
    const { owner, repo, pr } = match.groups;
    const response = await fetch(
      `${GITHUB_API}/repos/${owner}/${repo}/pulls/${pr}`,
      {
        method: "PATCH",
        headers: {
          ...buildHeaders(credentials.githubToken),
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ state: "closed" }),
      }
    );
    if (!response.ok && response.status !== 422) {
      throw new Error(`Failed to close PR #${pr}: ${response.status}`);
    }
  },

  validateCredentials: async (
    credentials: Record<string, string>
  ): Promise<boolean> => {
    try {
      const response = await fetch(`${GITHUB_API}/user`, {
        headers: buildHeaders(credentials.githubToken),
      });
      return response.ok;
    } catch {
      return false;
    }
  },
};
