import type { HarnessRecipe } from "./schemas";

const createStopConditions = (): HarnessRecipe["stopConditions"] => [
  "approval_cap_reached",
  "pr_cap_reached",
  "noop_loop_detected",
  "validator_loop_detected",
  "bridge_offline",
  "claude_unavailable",
  "dirty_worktree",
];

const createRerunPolicy = (): HarnessRecipe["rerunPolicy"] => ({
  triggers: [
    "input_changed",
    "new_evidence",
    "failed_validation",
    "manual_request",
    "merged_pr",
  ],
  inputHashStrategy: "artifact_hashes",
});

const approvalPolicy = "required_for_external_action";

export const DEFAULT_HARNESS_RECIPES = [
  {
    id: "product-brain",
    title: "Product Brain",
    version: 1,
    productMapTopic: "product_strategy",
    productMapLifecycle: "strategy",
    objectives: [
      "Build the repo-native company brief from codebase, market, and positioning evidence.",
    ],
    inputs: [".reflet/codebase", ".reflet/market", ".reflet/audience"],
    dependsOn: ["codebase-map", "market-competitor-research"],
    subagents: ["product-strategist", "critic-validator"],
    allowedTools: ["Read", "Grep", "Glob", "WebSearch"],
    outputs: [
      {
        artifactKind: "product_brain",
        path: ".reflet/strategy/product-brain.md",
        required: true,
      },
    ],
    validations: ["evidence_required", "productmap_topic_aligned"],
    stopConditions: createStopConditions(),
    sink: "artifacts",
    approvalPolicy,
    rerunPolicy: createRerunPolicy(),
  },
  {
    id: "codebase-map",
    title: "Codebase Map",
    version: 1,
    productMapTopic: "product_delivery",
    productMapLifecycle: "delivery",
    objectives: [
      "Map architecture, product surfaces, risk areas, and repo conventions.",
    ],
    inputs: ["README.md", "package manifests", "source routes"],
    dependsOn: [],
    subagents: ["codebase-mapper", "critic-validator"],
    allowedTools: ["Read", "Grep", "Glob", "Bash"],
    outputs: [
      {
        artifactKind: "codebase_map",
        path: ".reflet/codebase/map.md",
        required: true,
      },
    ],
    validations: ["evidence_required", "repo_paths_valid"],
    stopConditions: createStopConditions(),
    sink: "artifacts",
    approvalPolicy,
    rerunPolicy: createRerunPolicy(),
  },
  {
    id: "market-competitor-research",
    title: "Market & Competitor Research",
    version: 1,
    productMapTopic: "product_strategy",
    productMapLifecycle: "strategy",
    objectives: [
      "Find direct and adjacent competitors with source-backed positioning gaps.",
    ],
    inputs: [".reflet/codebase/map.md", "public web evidence"],
    dependsOn: ["codebase-map"],
    subagents: ["market-researcher", "competitor-scout", "critic-validator"],
    allowedTools: ["Read", "WebSearch", "WebFetch"],
    outputs: [
      {
        artifactKind: "market_map",
        path: ".reflet/market/competitors.md",
        required: true,
      },
    ],
    validations: ["evidence_required", "productmap_topic_aligned"],
    stopConditions: createStopConditions(),
    sink: "artifacts",
    approvalPolicy,
    rerunPolicy: createRerunPolicy(),
  },
  {
    id: "audience-use-cases",
    title: "Audience & Use Case Generation",
    version: 1,
    productMapTopic: "product_generation",
    productMapLifecycle: "generation",
    objectives: [
      "Generate ICP, personas, JTBD, and use cases from market pain and product evidence.",
    ],
    inputs: [
      ".reflet/market/competitors.md",
      ".reflet/strategy/product-brain.md",
    ],
    dependsOn: ["product-brain", "market-competitor-research"],
    subagents: ["audience-researcher", "use-case-designer", "critic-validator"],
    allowedTools: ["Read", "WebSearch"],
    outputs: [
      {
        artifactKind: "audience_research",
        path: ".reflet/audience/icp.md",
        required: true,
      },
      {
        artifactKind: "use_case_map",
        path: ".reflet/use-cases/map.md",
        required: true,
      },
    ],
    validations: ["evidence_required", "no_private_user_data"],
    stopConditions: createStopConditions(),
    sink: "artifacts",
    approvalPolicy,
    rerunPolicy: createRerunPolicy(),
  },
  {
    id: "product-gap-analysis",
    title: "Product Gap Analysis",
    version: 1,
    productMapTopic: "product_analysis",
    productMapLifecycle: "analysis",
    objectives: [
      "Turn use cases, competitor gaps, and codebase constraints into ranked opportunities.",
    ],
    inputs: [".reflet/use-cases/map.md", ".reflet/codebase/map.md"],
    dependsOn: ["audience-use-cases", "codebase-map"],
    subagents: ["product-strategist", "task-planner", "critic-validator"],
    allowedTools: ["Read", "Grep"],
    outputs: [
      {
        artifactKind: "product_gap_analysis",
        path: ".reflet/strategy/gaps.md",
        required: true,
      },
    ],
    validations: ["evidence_required", "productmap_topic_aligned"],
    stopConditions: createStopConditions(),
    sink: "artifacts",
    approvalPolicy,
    rerunPolicy: createRerunPolicy(),
  },
  {
    id: "posthog-audit",
    title: "PostHog Audit",
    version: 1,
    productMapTopic: "product_analysis",
    productMapLifecycle: "analysis",
    objectives: [
      "Map use cases to analytics events and identify missing product instrumentation.",
    ],
    inputs: [".reflet/use-cases/map.md", ".reflet/codebase/map.md"],
    dependsOn: ["audience-use-cases"],
    subagents: ["posthog-analyst", "critic-validator"],
    allowedTools: ["Read", "Grep"],
    outputs: [
      {
        artifactKind: "posthog_audit",
        path: ".reflet/analytics/posthog-audit.md",
        required: true,
      },
    ],
    validations: ["evidence_required", "action_requires_approval"],
    stopConditions: createStopConditions(),
    sink: "artifacts",
    approvalPolicy,
    rerunPolicy: createRerunPolicy(),
  },
  {
    id: "bug-finder",
    title: "Bug Finder",
    version: 1,
    productMapTopic: "product_delivery",
    productMapLifecycle: "delivery",
    objectives: [
      "Find likely bugs from use cases, source paths, and recent product gaps.",
    ],
    inputs: [".reflet/use-cases/map.md", ".reflet/strategy/gaps.md"],
    dependsOn: ["product-gap-analysis"],
    subagents: ["bug-finder", "critic-validator"],
    allowedTools: ["Read", "Grep", "Bash"],
    outputs: [
      {
        artifactKind: "bug_report",
        path: ".reflet/tasks/bugs.md",
        required: false,
      },
    ],
    validations: ["evidence_required", "repo_paths_valid"],
    stopConditions: createStopConditions(),
    sink: "artifacts",
    approvalPolicy,
    rerunPolicy: createRerunPolicy(),
  },
  {
    id: "task-planner",
    title: "Task Planner",
    version: 1,
    productMapTopic: "product_delivery",
    productMapLifecycle: "delivery",
    objectives: [
      "Convert validated opportunities into PR-ready tasks with acceptance criteria.",
    ],
    inputs: [".reflet/strategy/gaps.md", ".reflet/tasks/bugs.md"],
    dependsOn: ["product-gap-analysis"],
    subagents: ["task-planner", "critic-validator"],
    allowedTools: ["Read", "Grep"],
    outputs: [
      {
        artifactKind: "task_plan",
        path: ".reflet/tasks/plan.md",
        required: true,
      },
    ],
    validations: ["evidence_required", "action_requires_approval"],
    stopConditions: createStopConditions(),
    sink: "artifacts",
    approvalPolicy,
    rerunPolicy: createRerunPolicy(),
  },
  {
    id: "pr-builder",
    title: "PR Builder",
    version: 1,
    productMapTopic: "product_delivery",
    productMapLifecycle: "delivery",
    objectives: [
      "Implement approved tasks in an isolated worktree and open a draft PR.",
    ],
    inputs: [".reflet/tasks/plan.md"],
    dependsOn: ["task-planner"],
    subagents: ["implementation-agent", "critic-validator"],
    allowedTools: ["Read", "Edit", "Bash", "Grep", "Glob"],
    outputs: [
      {
        artifactKind: "pull_request_draft",
        path: ".reflet/delivery/pr-draft.md",
        required: true,
      },
    ],
    validations: ["repo_paths_valid", "action_requires_approval"],
    stopConditions: createStopConditions(),
    approvalPolicy: "always_required",
    rerunPolicy: createRerunPolicy(),
  },
  {
    id: "pr-reviewer",
    title: "PR Reviewer",
    version: 1,
    productMapTopic: "people_process",
    productMapLifecycle: "people_process",
    objectives: [
      "Review each draft PR in a separate Claude request before user approval.",
    ],
    inputs: ["draft PR diff", ".reflet/tasks/plan.md"],
    dependsOn: ["pr-builder"],
    subagents: ["pr-reviewer", "critic-validator"],
    allowedTools: ["Read", "Bash", "Grep"],
    outputs: [
      {
        artifactKind: "pull_request_review",
        path: ".reflet/delivery/pr-review.md",
        required: true,
      },
    ],
    validations: ["reviewer_passed", "action_requires_approval"],
    stopConditions: createStopConditions(),
    approvalPolicy: "always_required",
    rerunPolicy: createRerunPolicy(),
  },
  {
    id: "changelog-growth",
    title: "Changelog & Growth Drafts",
    version: 1,
    productMapTopic: "product_generation",
    productMapLifecycle: "generation",
    objectives: [
      "Turn shipped work into changelog, blog, and Reddit-ready drafts.",
    ],
    inputs: ["merged PR", ".reflet/strategy/product-brain.md"],
    dependsOn: ["pr-reviewer"],
    subagents: ["growth-writer", "critic-validator"],
    allowedTools: ["Read", "WebSearch"],
    outputs: [
      {
        artifactKind: "growth_draft",
        path: ".reflet/out/growth/drafts.json",
        required: true,
      },
    ],
    validations: ["evidence_required", "action_requires_approval"],
    stopConditions: createStopConditions(),
    sink: "documents",
    approvalPolicy: "always_required",
    rerunPolicy: createRerunPolicy(),
  },
  {
    id: "marketing-reddit",
    title: "Marketing Reddit Replies",
    version: 1,
    productMapTopic: "product_generation",
    productMapLifecycle: "generation",
    objectives: [
      "Find real, currently-open Reddit threads where a helpful reply mentioning the product fits, verify each thread exists, and draft a non-spammy reply.",
    ],
    inputs: [".reflet/strategy/product-brain.md", ".reflet/audience/icp.md"],
    dependsOn: [],
    subagents: ["market-researcher", "critic-validator"],
    allowedTools: ["Read", "Bash(curl *)"],
    outputs: [
      {
        artifactKind: "community_drafts",
        path: ".reflet/out/marketing/reddit.json",
        required: true,
      },
    ],
    validations: ["evidence_required"],
    stopConditions: createStopConditions(),
    sink: "documents",
    approvalPolicy,
    rerunPolicy: createRerunPolicy(),
  },
] satisfies readonly HarnessRecipe[];
