/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as admin_api___tests___test_helpers from "../admin_api/__tests__/test_helpers.js";
import type * as admin_api_duplicates from "../admin_api/duplicates.js";
import type * as admin_api_feedback from "../admin_api/feedback.js";
import type * as admin_api_members from "../admin_api/members.js";
import type * as admin_api_milestones from "../admin_api/milestones.js";
import type * as admin_api_organization from "../admin_api/organization.js";
import type * as admin_api_releases from "../admin_api/releases.js";
import type * as admin_api_screenshots from "../admin_api/screenshots.js";
import type * as admin_api_statuses from "../admin_api/statuses.js";
import type * as admin_api_survey from "../admin_api/survey.js";
import type * as admin_api_survey_analytics from "../admin_api/survey_analytics.js";
import type * as admin_api_tableFields from "../admin_api/tableFields.js";
import type * as admin_api_tags from "../admin_api/tags.js";
import type * as ai_chat from "../ai/chat.js";
import type * as ai_context from "../ai/context.js";
import type * as ai_runtimes from "../ai/runtimes.js";
import type * as auth_auth from "../auth/auth.js";
import type * as auth_helpers from "../auth/helpers.js";
import type * as auth_queries from "../auth/queries.js";
import type * as autopilot_autonomy from "../autopilot/autonomy.js";
import type * as autopilot_billing_gate from "../autopilot/billing_gate.js";
import type * as autopilot_ceo_chat from "../autopilot/ceo_chat.js";
import type * as autopilot_chain from "../autopilot/chain.js";
import type * as autopilot_codebase___tests___mock_helpers from "../autopilot/codebase/__tests__/mock_helpers.js";
import type * as autopilot_codebase_actions from "../autopilot/codebase/actions.js";
import type * as autopilot_codebase_explorer from "../autopilot/codebase/explorer.js";
import type * as autopilot_codebase_mutations from "../autopilot/codebase/mutations.js";
import type * as autopilot_codebase_octokit_helpers from "../autopilot/codebase/octokit_helpers.js";
import type * as autopilot_codebase_prompts from "../autopilot/codebase/prompts.js";
import type * as autopilot_codebase_queries from "../autopilot/codebase/queries.js";
import type * as autopilot_codebase_tools from "../autopilot/codebase/tools.js";
import type * as autopilot_competitors from "../autopilot/competitors.js";
import type * as autopilot_config from "../autopilot/config.js";
import type * as autopilot_config_mutations from "../autopilot/config_mutations.js";
import type * as autopilot_config_task_caps from "../autopilot/config_task_caps.js";
import type * as autopilot_context from "../autopilot/context.js";
import type * as autopilot_cost_guard from "../autopilot/cost_guard.js";
import type * as autopilot_dedup from "../autopilot/dedup.js";
import type * as autopilot_documents from "../autopilot/documents.js";
import type * as autopilot_execution_lifecycle from "../autopilot/execution_lifecycle.js";
import type * as autopilot_gate from "../autopilot/gate.js";
import type * as autopilot_guards from "../autopilot/guards.js";
import type * as autopilot_harness_bridge from "../autopilot/harness/bridge.js";
import type * as autopilot_harness_guards from "../autopilot/harness/guards.js";
import type * as autopilot_harness_mutations from "../autopilot/harness/mutations.js";
import type * as autopilot_harness_queries from "../autopilot/harness/queries.js";
import type * as autopilot_health from "../autopilot/health.js";
import type * as autopilot_health_checks from "../autopilot/health_checks.js";
import type * as autopilot_heartbeat from "../autopilot/heartbeat.js";
import type * as autopilot_integrations_email from "../autopilot/integrations/email.js";
import type * as autopilot_integrations_social from "../autopilot/integrations/social.js";
import type * as autopilot_lib_identifier from "../autopilot/lib/identifier.js";
import type * as autopilot_maintenance from "../autopilot/maintenance.js";
import type * as autopilot_mutations_auth from "../autopilot/mutations/auth.js";
import type * as autopilot_mutations_community_posts from "../autopilot/mutations/community_posts.js";
import type * as autopilot_mutations_config from "../autopilot/mutations/config.js";
import type * as autopilot_mutations_documents from "../autopilot/mutations/documents.js";
import type * as autopilot_mutations_feedback_links from "../autopilot/mutations/feedback_links.js";
import type * as autopilot_mutations_inbox from "../autopilot/mutations/inbox.js";
import type * as autopilot_mutations_knowledge from "../autopilot/mutations/knowledge.js";
import type * as autopilot_mutations_labels from "../autopilot/mutations/labels.js";
import type * as autopilot_mutations_personas from "../autopilot/mutations/personas.js";
import type * as autopilot_mutations_product_profile from "../autopilot/mutations/product_profile.js";
import type * as autopilot_mutations_reports from "../autopilot/mutations/reports.js";
import type * as autopilot_mutations_use_cases from "../autopilot/mutations/use_cases.js";
import type * as autopilot_mutations_views from "../autopilot/mutations/views.js";
import type * as autopilot_mutations_work from "../autopilot/mutations/work.js";
import type * as autopilot_onboarding_tasks from "../autopilot/onboarding_tasks.js";
import type * as autopilot_ownership from "../autopilot/ownership.js";
import type * as autopilot_priorities from "../autopilot/priorities.js";
import type * as autopilot_queries_activity from "../autopilot/queries/activity.js";
import type * as autopilot_queries_auth from "../autopilot/queries/auth.js";
import type * as autopilot_queries_chain from "../autopilot/queries/chain.js";
import type * as autopilot_queries_competitors from "../autopilot/queries/competitors.js";
import type * as autopilot_queries_config from "../autopilot/queries/config.js";
import type * as autopilot_queries_dashboard from "../autopilot/queries/dashboard.js";
import type * as autopilot_queries_documents from "../autopilot/queries/documents.js";
import type * as autopilot_queries_feedback_links from "../autopilot/queries/feedback_links.js";
import type * as autopilot_queries_inbox from "../autopilot/queries/inbox.js";
import type * as autopilot_queries_knowledge from "../autopilot/queries/knowledge.js";
import type * as autopilot_queries_labels from "../autopilot/queries/labels.js";
import type * as autopilot_queries_leads from "../autopilot/queries/leads.js";
import type * as autopilot_queries_productProfile from "../autopilot/queries/productProfile.js";
import type * as autopilot_queries_reports from "../autopilot/queries/reports.js";
import type * as autopilot_queries_revenue from "../autopilot/queries/revenue.js";
import type * as autopilot_queries_tasks_public from "../autopilot/queries/tasks_public.js";
import type * as autopilot_queries_views from "../autopilot/queries/views.js";
import type * as autopilot_queries_work from "../autopilot/queries/work.js";
import type * as autopilot_repo_analysis from "../autopilot/repo_analysis.js";
import type * as autopilot_reports from "../autopilot/reports.js";
import type * as autopilot_reset_mutations from "../autopilot/reset/mutations.js";
import type * as autopilot_reset_scope from "../autopilot/reset/scope.js";
import type * as autopilot_revenue_actions from "../autopilot/revenue_actions.js";
import type * as autopilot_revenue_queries from "../autopilot/revenue_queries.js";
import type * as autopilot_role_context from "../autopilot/role_context.js";
import type * as autopilot_role_schedule from "../autopilot/role_schedule.js";
import type * as autopilot_role_skills_ceo_coordination from "../autopilot/role_skills/ceo/coordination.js";
import type * as autopilot_role_skills_ceo_queries from "../autopilot/role_skills/ceo/queries.js";
import type * as autopilot_role_skills_ceo_reports from "../autopilot/role_skills/ceo/reports.js";
import type * as autopilot_role_skills_ceo_runtime from "../autopilot/role_skills/ceo/runtime.js";
import type * as autopilot_role_skills_ceo_tools from "../autopilot/role_skills/ceo_tools.js";
import type * as autopilot_role_skills_chain_producers from "../autopilot/role_skills/chain_producers.js";
import type * as autopilot_role_skills_community_discovery from "../autopilot/role_skills/community_discovery.js";
import type * as autopilot_role_skills_cto from "../autopilot/role_skills/cto.js";
import type * as autopilot_role_skills_growth_content_enricher from "../autopilot/role_skills/growth/content_enricher.js";
import type * as autopilot_role_skills_growth_content_generation from "../autopilot/role_skills/growth/content_generation.js";
import type * as autopilot_role_skills_growth_content_storage from "../autopilot/role_skills/growth/content_storage.js";
import type * as autopilot_role_skills_growth_discovery from "../autopilot/role_skills/growth/discovery.js";
import type * as autopilot_role_skills_growth_drafts_producer from "../autopilot/role_skills/growth/drafts/producer.js";
import type * as autopilot_role_skills_growth_gap_assessment from "../autopilot/role_skills/growth/gap_assessment.js";
import type * as autopilot_role_skills_growth_market_research from "../autopilot/role_skills/growth/market_research.js";
import type * as autopilot_role_skills_growth_product_context from "../autopilot/role_skills/growth/product_context.js";
import type * as autopilot_role_skills_growth_query_builder from "../autopilot/role_skills/growth/query_builder.js";
import type * as autopilot_role_skills_growth_relevance_scorer from "../autopilot/role_skills/growth/relevance_scorer.js";
import type * as autopilot_role_skills_growth_research_helpers from "../autopilot/role_skills/growth/research_helpers.js";
import type * as autopilot_role_skills_models from "../autopilot/role_skills/models.js";
import type * as autopilot_role_skills_pm_analysis from "../autopilot/role_skills/pm/analysis.js";
import type * as autopilot_role_skills_pm_initiatives from "../autopilot/role_skills/pm/initiatives.js";
import type * as autopilot_role_skills_pm_queries from "../autopilot/role_skills/pm/queries.js";
import type * as autopilot_role_skills_prompts from "../autopilot/role_skills/prompts.js";
import type * as autopilot_role_skills_sales_discovery from "../autopilot/role_skills/sales_discovery.js";
import type * as autopilot_role_skills_sales_mutations from "../autopilot/role_skills/sales_mutations.js";
import type * as autopilot_role_skills_sales_prospecting from "../autopilot/role_skills/sales_prospecting.js";
import type * as autopilot_role_skills_sales_queries from "../autopilot/role_skills/sales_queries.js";
import type * as autopilot_role_skills_shared_exa from "../autopilot/role_skills/shared_exa.js";
import type * as autopilot_role_skills_shared_generation from "../autopilot/role_skills/shared_generation.js";
import type * as autopilot_role_skills_shared_search from "../autopilot/role_skills/shared_search.js";
import type * as autopilot_role_skills_shared_web from "../autopilot/role_skills/shared_web.js";
import type * as autopilot_role_skills_support from "../autopilot/role_skills/support.js";
import type * as autopilot_role_skills_validation_community_posts from "../autopilot/role_skills/validation/community_posts.js";
import type * as autopilot_role_skills_validator from "../autopilot/role_skills/validator.js";
import type * as autopilot_role_skills_validator_prompts from "../autopilot/role_skills/validator_prompts.js";
import type * as autopilot_runtime_executor from "../autopilot/runtime/executor.js";
import type * as autopilot_runtime_lifecycle from "../autopilot/runtime/lifecycle.js";
import type * as autopilot_runtime_mutations from "../autopilot/runtime/mutations.js";
import type * as autopilot_runtime_policy from "../autopilot/runtime/policy.js";
import type * as autopilot_runtime_queries from "../autopilot/runtime/queries.js";
import type * as autopilot_runtime_state from "../autopilot/runtime/state.js";
import type * as autopilot_runtime_view from "../autopilot/runtime/view.js";
import type * as autopilot_sales_mutations from "../autopilot/sales_mutations.js";
import type * as autopilot_schedule_build from "../autopilot/schedule/build.js";
import type * as autopilot_schedule_signals from "../autopilot/schedule/signals.js";
import type * as autopilot_schedule_types from "../autopilot/schedule/types.js";
import type * as autopilot_schema_index from "../autopilot/schema/index.js";
import type * as autopilot_schema_validators from "../autopilot/schema/validators.js";
import type * as autopilot_self_heal from "../autopilot/self_heal.js";
import type * as autopilot_task_mutations from "../autopilot/task_mutations.js";
import type * as autopilot_task_queries from "../autopilot/task_queries.js";
import type * as billing_actions from "../billing/actions.js";
import type * as billing_effective_tier from "../billing/effective_tier.js";
import type * as billing_internal from "../billing/internal.js";
import type * as billing_lib from "../billing/lib.js";
import type * as billing_queries from "../billing/queries.js";
import type * as billing_stripe from "../billing/stripe.js";
import type * as billing_tableFields from "../billing/tableFields.js";
import type * as billing_utils from "../billing/utils.js";
import type * as changelog_ai_actions from "../changelog/ai_actions.js";
import type * as changelog_ai_matching from "../changelog/ai_matching.js";
import type * as changelog_ai_matching_helpers from "../changelog/ai_matching_helpers.js";
import type * as changelog_feedback_linking from "../changelog/feedback_linking.js";
import type * as changelog_lib_action_helpers from "../changelog/lib/action_helpers.js";
import type * as changelog_lib_ai_helpers from "../changelog/lib/ai_helpers.js";
import type * as changelog_lib_commit_grouping from "../changelog/lib/commit_grouping.js";
import type * as changelog_lib_github_fetch from "../changelog/lib/github_fetch.js";
import type * as changelog_mutations from "../changelog/mutations.js";
import type * as changelog_notifications from "../changelog/notifications.js";
import type * as changelog_notifications_helpers from "../changelog/notifications_helpers.js";
import type * as changelog_queries from "../changelog/queries.js";
import type * as changelog_release_commits from "../changelog/release_commits.js";
import type * as changelog_release_lifecycle from "../changelog/release_lifecycle.js";
import type * as changelog_release_notes_ai from "../changelog/release_notes_ai.js";
import type * as changelog_release_versions from "../changelog/release_versions.js";
import type * as changelog_releases from "../changelog/releases.js";
import type * as changelog_releases_internal from "../changelog/releases_internal.js";
import type * as changelog_retroactive from "../changelog/retroactive.js";
import type * as changelog_retroactive_actions from "../changelog/retroactive_actions.js";
import type * as changelog_retroactive_mutations from "../changelog/retroactive_mutations.js";
import type * as changelog_rss from "../changelog/rss.js";
import type * as changelog_scheduling from "../changelog/scheduling.js";
import type * as changelog_subscriptions from "../changelog/subscriptions.js";
import type * as changelog_tableFields from "../changelog/tableFields.js";
import type * as crons from "../crons.js";
import type * as domains_actions from "../domains/actions.js";
import type * as domains_crons from "../domains/crons.js";
import type * as domains_internal from "../domains/internal.js";
import type * as domains_publicMutations from "../domains/publicMutations.js";
import type * as domains_queries from "../domains/queries.js";
import type * as domains_vercel from "../domains/vercel.js";
import type * as duplicates_detection from "../duplicates/detection.js";
import type * as duplicates_merge from "../duplicates/merge.js";
import type * as duplicates_queries from "../duplicates/queries.js";
import type * as duplicates_tableFields from "../duplicates/tableFields.js";
import type * as email_analytics from "../email/analytics.js";
import type * as email_health from "../email/health.js";
import type * as email_renderer from "../email/renderer.js";
import type * as email_send from "../email/send.js";
import type * as email_suppression from "../email/suppression.js";
import type * as email_tableFields from "../email/tableFields.js";
import type * as feedback_actions from "../feedback/actions.js";
import type * as feedback_actions_manage from "../feedback/actions_manage.js";
import type * as feedback_api_admin from "../feedback/api_admin.js";
import type * as feedback_api_auth from "../feedback/api_auth.js";
import type * as feedback_api_keys from "../feedback/api_keys.js";
import type * as feedback_api_public_mutations from "../feedback/api_public_mutations.js";
import type * as feedback_api_public_queries from "../feedback/api_public_queries.js";
import type * as feedback_api_public_reads from "../feedback/api_public_reads.js";
import type * as feedback_auto_tagging_actions from "../feedback/auto_tagging_actions.js";
import type * as feedback_auto_tagging_mutations from "../feedback/auto_tagging_mutations.js";
import type * as feedback_auto_tagging_queries from "../feedback/auto_tagging_queries.js";
import type * as feedback_clarification from "../feedback/clarification.js";
import type * as feedback_clarification_difficulty from "../feedback/clarification_difficulty.js";
import type * as feedback_clarification_draft_reply from "../feedback/clarification_draft_reply.js";
import type * as feedback_cleanup from "../feedback/cleanup.js";
import type * as feedback_comments from "../feedback/comments.js";
import type * as feedback_feature_check from "../feedback/feature_check.js";
import type * as feedback_feature_check_action from "../feedback/feature_check_action.js";
import type * as feedback_importance from "../feedback/importance.js";
import type * as feedback_list from "../feedback/list.js";
import type * as feedback_mutations from "../feedback/mutations.js";
import type * as feedback_queries from "../feedback/queries.js";
import type * as feedback_roadmap from "../feedback/roadmap.js";
import type * as feedback_screenshots from "../feedback/screenshots.js";
import type * as feedback_stale from "../feedback/stale.js";
import type * as feedback_status_utils from "../feedback/status_utils.js";
import type * as feedback_subscriptions from "../feedback/subscriptions.js";
import type * as feedback_tableFields from "../feedback/tableFields.js";
import type * as feedback_tags_mutations from "../feedback/tags_mutations.js";
import type * as feedback_tags_queries from "../feedback/tags_queries.js";
import type * as feedback_trash from "../feedback/trash.js";
import type * as feedback_votes from "../feedback/votes.js";
import type * as healthCheck from "../healthCheck.js";
import type * as http from "../http.js";
import type * as http_admin_content from "../http/admin_content.js";
import type * as http_admin_content_surveys from "../http/admin_content_surveys.js";
import type * as http_admin_feedback from "../http/admin_feedback.js";
import type * as http_admin_management from "../http/admin_management.js";
import type * as http_ai_api from "../http/ai_api.js";
import type * as http_bridge_api from "../http/bridge_api.js";
import type * as http_github_api from "../http/github_api.js";
import type * as http_github_api_helpers from "../http/github_api_helpers.js";
import type * as http_github_api_reads from "../http/github_api_reads.js";
import type * as http_github_webhook from "../http/github_webhook.js";
import type * as http_helpers from "../http/helpers.js";
import type * as http_lib_api_auth from "../http/lib/api_auth.js";
import type * as http_lib_api_helpers from "../http/lib/api_helpers.js";
import type * as http_public_api from "../http/public_api.js";
import type * as http_public_api_feedback_reads from "../http/public_api_feedback_reads.js";
import type * as http_public_api_feedback_writes from "../http/public_api_feedback_writes.js";
import type * as http_public_api_surveys from "../http/public_api_surveys.js";
import type * as integrations_github_actions_node from "../integrations/github/actions_node.js";
import type * as integrations_github_client_actions from "../integrations/github/client_actions.js";
import type * as integrations_github_code_search from "../integrations/github/code_search.js";
import type * as integrations_github_connection_actions from "../integrations/github/connection_actions.js";
import type * as integrations_github_connection_mutations from "../integrations/github/connection_mutations.js";
import type * as integrations_github_exploration_tools from "../integrations/github/exploration_tools.js";
import type * as integrations_github_fetch_actions from "../integrations/github/fetch_actions.js";
import type * as integrations_github_github_helpers from "../integrations/github/github_helpers.js";
import type * as integrations_github_installation_mutations from "../integrations/github/installation_mutations.js";
import type * as integrations_github_issue_imports from "../integrations/github/issue_imports.js";
import type * as integrations_github_issue_mutations from "../integrations/github/issue_mutations.js";
import type * as integrations_github_issue_queries from "../integrations/github/issue_queries.js";
import type * as integrations_github_node_actions from "../integrations/github/node_actions.js";
import type * as integrations_github_product_exploration from "../integrations/github/product_exploration.js";
import type * as integrations_github_product_exploration_helpers from "../integrations/github/product_exploration_helpers.js";
import type * as integrations_github_project_setup_actions from "../integrations/github/project_setup_actions.js";
import type * as integrations_github_project_setup_mutations from "../integrations/github/project_setup_mutations.js";
import type * as integrations_github_project_setup_queries from "../integrations/github/project_setup_queries.js";
import type * as integrations_github_project_setup_shared from "../integrations/github/project_setup_shared.js";
import type * as integrations_github_queries from "../integrations/github/queries.js";
import type * as integrations_github_release_actions from "../integrations/github/release_actions.js";
import type * as integrations_github_repo_analysis from "../integrations/github/repo_analysis.js";
import type * as integrations_github_sync from "../integrations/github/sync.js";
import type * as integrations_github_sync_mutations from "../integrations/github/sync_mutations.js";
import type * as integrations_github_tableFields from "../integrations/github/tableFields.js";
import type * as integrations_github_webhook_issue_processors from "../integrations/github/webhook_issue_processors.js";
import type * as integrations_github_webhook_release_processors from "../integrations/github/webhook_release_processors.js";
import type * as integrations_website_references from "../integrations/website_references.js";
import type * as mcp_handler from "../mcp/handler.js";
import type * as mcp_protocol from "../mcp/protocol.js";
import type * as mcp_tools from "../mcp/tools.js";
import type * as mcp_tools_comments from "../mcp/tools_comments.js";
import type * as mcp_tools_feedback from "../mcp/tools_feedback.js";
import type * as mcp_tools_milestones from "../mcp/tools_milestones.js";
import type * as mcp_tools_organization from "../mcp/tools_organization.js";
import type * as mcp_tools_releases from "../mcp/tools_releases.js";
import type * as mcp_tools_shared from "../mcp/tools_shared.js";
import type * as mcp_tools_tags from "../mcp/tools_tags.js";
import type * as migrations_cleanup_board_fields from "../migrations/cleanup_board_fields.js";
import type * as notifications_preferences from "../notifications/preferences.js";
import type * as notifications_push from "../notifications/push.js";
import type * as notifications_push_queries from "../notifications/push_queries.js";
import type * as notifications_queries from "../notifications/queries.js";
import type * as notifications_shipped from "../notifications/shipped.js";
import type * as notifications_shipped_helpers from "../notifications/shipped_helpers.js";
import type * as notifications_tableFields from "../notifications/tableFields.js";
import type * as notifications_weekly_digest from "../notifications/weekly_digest.js";
import type * as notifications_weekly_digest_helpers from "../notifications/weekly_digest_helpers.js";
import type * as organizations_actions from "../organizations/actions.js";
import type * as organizations_invitation_queries from "../organizations/invitation_queries.js";
import type * as organizations_invitations from "../organizations/invitations.js";
import type * as organizations_members from "../organizations/members.js";
import type * as organizations_milestones_mutations from "../organizations/milestones_mutations.js";
import type * as organizations_milestones_queries from "../organizations/milestones_queries.js";
import type * as organizations_mutations from "../organizations/mutations.js";
import type * as organizations_onboarding from "../organizations/onboarding.js";
import type * as organizations_queries from "../organizations/queries.js";
import type * as organizations_statuses from "../organizations/statuses.js";
import type * as organizations_statuses_queries from "../organizations/statuses_queries.js";
import type * as organizations_super_admin_analytics from "../organizations/super_admin_analytics.js";
import type * as organizations_super_admin_queries from "../organizations/super_admin_queries.js";
import type * as organizations_tableFields from "../organizations/tableFields.js";
import type * as organizations_tag_manager from "../organizations/tag_manager.js";
import type * as organizations_tag_manager_actions from "../organizations/tag_manager_actions.js";
import type * as privateData from "../privateData.js";
import type * as shared_access from "../shared/access.js";
import type * as shared_constants from "../shared/constants.js";
import type * as shared_env from "../shared/env.js";
import type * as shared_slug from "../shared/slug.js";
import type * as shared_text_formatters from "../shared/text_formatters.js";
import type * as shared_utils from "../shared/utils.js";
import type * as shared_validators from "../shared/validators.js";
import type * as sitemap_public from "../sitemap_public.js";
import type * as status_healthCheck from "../status/healthCheck.js";
import type * as status_incidents from "../status/incidents.js";
import type * as status_monitors from "../status/monitors.js";
import type * as status_publicQueries from "../status/publicQueries.js";
import type * as status_subscriptions from "../status/subscriptions.js";
import type * as status_tableFields from "../status/tableFields.js";
import type * as storage from "../storage.js";
import type * as support_conversation_mutations from "../support/conversation_mutations.js";
import type * as support_conversation_queries from "../support/conversation_queries.js";
import type * as support_message_mutations from "../support/message_mutations.js";
import type * as support_message_queries from "../support/message_queries.js";
import type * as support_tableFields from "../support/tableFields.js";
import type * as surveys_lib_analytics_helpers from "../surveys/lib/analytics_helpers.js";
import type * as surveys_mutations from "../surveys/mutations.js";
import type * as surveys_queries from "../surveys/queries.js";
import type * as surveys_questions from "../surveys/questions.js";
import type * as surveys_responses from "../surveys/responses.js";
import type * as surveys_tableFields from "../surveys/tableFields.js";
import type * as todos from "../todos.js";
import type * as widget_admin_mutations from "../widget/admin_mutations.js";
import type * as widget_admin_queries from "../widget/admin_queries.js";
import type * as widget_public from "../widget/public.js";
import type * as widget_tableFields from "../widget/tableFields.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "admin_api/__tests__/test_helpers": typeof admin_api___tests___test_helpers;
  "admin_api/duplicates": typeof admin_api_duplicates;
  "admin_api/feedback": typeof admin_api_feedback;
  "admin_api/members": typeof admin_api_members;
  "admin_api/milestones": typeof admin_api_milestones;
  "admin_api/organization": typeof admin_api_organization;
  "admin_api/releases": typeof admin_api_releases;
  "admin_api/screenshots": typeof admin_api_screenshots;
  "admin_api/statuses": typeof admin_api_statuses;
  "admin_api/survey": typeof admin_api_survey;
  "admin_api/survey_analytics": typeof admin_api_survey_analytics;
  "admin_api/tableFields": typeof admin_api_tableFields;
  "admin_api/tags": typeof admin_api_tags;
  "ai/chat": typeof ai_chat;
  "ai/context": typeof ai_context;
  "ai/runtimes": typeof ai_runtimes;
  "auth/auth": typeof auth_auth;
  "auth/helpers": typeof auth_helpers;
  "auth/queries": typeof auth_queries;
  "autopilot/autonomy": typeof autopilot_autonomy;
  "autopilot/billing_gate": typeof autopilot_billing_gate;
  "autopilot/ceo_chat": typeof autopilot_ceo_chat;
  "autopilot/chain": typeof autopilot_chain;
  "autopilot/codebase/__tests__/mock_helpers": typeof autopilot_codebase___tests___mock_helpers;
  "autopilot/codebase/actions": typeof autopilot_codebase_actions;
  "autopilot/codebase/explorer": typeof autopilot_codebase_explorer;
  "autopilot/codebase/mutations": typeof autopilot_codebase_mutations;
  "autopilot/codebase/octokit_helpers": typeof autopilot_codebase_octokit_helpers;
  "autopilot/codebase/prompts": typeof autopilot_codebase_prompts;
  "autopilot/codebase/queries": typeof autopilot_codebase_queries;
  "autopilot/codebase/tools": typeof autopilot_codebase_tools;
  "autopilot/competitors": typeof autopilot_competitors;
  "autopilot/config": typeof autopilot_config;
  "autopilot/config_mutations": typeof autopilot_config_mutations;
  "autopilot/config_task_caps": typeof autopilot_config_task_caps;
  "autopilot/context": typeof autopilot_context;
  "autopilot/cost_guard": typeof autopilot_cost_guard;
  "autopilot/dedup": typeof autopilot_dedup;
  "autopilot/documents": typeof autopilot_documents;
  "autopilot/execution_lifecycle": typeof autopilot_execution_lifecycle;
  "autopilot/gate": typeof autopilot_gate;
  "autopilot/guards": typeof autopilot_guards;
  "autopilot/harness/bridge": typeof autopilot_harness_bridge;
  "autopilot/harness/guards": typeof autopilot_harness_guards;
  "autopilot/harness/mutations": typeof autopilot_harness_mutations;
  "autopilot/harness/queries": typeof autopilot_harness_queries;
  "autopilot/health": typeof autopilot_health;
  "autopilot/health_checks": typeof autopilot_health_checks;
  "autopilot/heartbeat": typeof autopilot_heartbeat;
  "autopilot/integrations/email": typeof autopilot_integrations_email;
  "autopilot/integrations/social": typeof autopilot_integrations_social;
  "autopilot/lib/identifier": typeof autopilot_lib_identifier;
  "autopilot/maintenance": typeof autopilot_maintenance;
  "autopilot/mutations/auth": typeof autopilot_mutations_auth;
  "autopilot/mutations/community_posts": typeof autopilot_mutations_community_posts;
  "autopilot/mutations/config": typeof autopilot_mutations_config;
  "autopilot/mutations/documents": typeof autopilot_mutations_documents;
  "autopilot/mutations/feedback_links": typeof autopilot_mutations_feedback_links;
  "autopilot/mutations/inbox": typeof autopilot_mutations_inbox;
  "autopilot/mutations/knowledge": typeof autopilot_mutations_knowledge;
  "autopilot/mutations/labels": typeof autopilot_mutations_labels;
  "autopilot/mutations/personas": typeof autopilot_mutations_personas;
  "autopilot/mutations/product_profile": typeof autopilot_mutations_product_profile;
  "autopilot/mutations/reports": typeof autopilot_mutations_reports;
  "autopilot/mutations/use_cases": typeof autopilot_mutations_use_cases;
  "autopilot/mutations/views": typeof autopilot_mutations_views;
  "autopilot/mutations/work": typeof autopilot_mutations_work;
  "autopilot/onboarding_tasks": typeof autopilot_onboarding_tasks;
  "autopilot/ownership": typeof autopilot_ownership;
  "autopilot/priorities": typeof autopilot_priorities;
  "autopilot/queries/activity": typeof autopilot_queries_activity;
  "autopilot/queries/auth": typeof autopilot_queries_auth;
  "autopilot/queries/chain": typeof autopilot_queries_chain;
  "autopilot/queries/competitors": typeof autopilot_queries_competitors;
  "autopilot/queries/config": typeof autopilot_queries_config;
  "autopilot/queries/dashboard": typeof autopilot_queries_dashboard;
  "autopilot/queries/documents": typeof autopilot_queries_documents;
  "autopilot/queries/feedback_links": typeof autopilot_queries_feedback_links;
  "autopilot/queries/inbox": typeof autopilot_queries_inbox;
  "autopilot/queries/knowledge": typeof autopilot_queries_knowledge;
  "autopilot/queries/labels": typeof autopilot_queries_labels;
  "autopilot/queries/leads": typeof autopilot_queries_leads;
  "autopilot/queries/productProfile": typeof autopilot_queries_productProfile;
  "autopilot/queries/reports": typeof autopilot_queries_reports;
  "autopilot/queries/revenue": typeof autopilot_queries_revenue;
  "autopilot/queries/tasks_public": typeof autopilot_queries_tasks_public;
  "autopilot/queries/views": typeof autopilot_queries_views;
  "autopilot/queries/work": typeof autopilot_queries_work;
  "autopilot/repo_analysis": typeof autopilot_repo_analysis;
  "autopilot/reports": typeof autopilot_reports;
  "autopilot/reset/mutations": typeof autopilot_reset_mutations;
  "autopilot/reset/scope": typeof autopilot_reset_scope;
  "autopilot/revenue_actions": typeof autopilot_revenue_actions;
  "autopilot/revenue_queries": typeof autopilot_revenue_queries;
  "autopilot/role_context": typeof autopilot_role_context;
  "autopilot/role_schedule": typeof autopilot_role_schedule;
  "autopilot/role_skills/ceo/coordination": typeof autopilot_role_skills_ceo_coordination;
  "autopilot/role_skills/ceo/queries": typeof autopilot_role_skills_ceo_queries;
  "autopilot/role_skills/ceo/reports": typeof autopilot_role_skills_ceo_reports;
  "autopilot/role_skills/ceo/runtime": typeof autopilot_role_skills_ceo_runtime;
  "autopilot/role_skills/ceo_tools": typeof autopilot_role_skills_ceo_tools;
  "autopilot/role_skills/chain_producers": typeof autopilot_role_skills_chain_producers;
  "autopilot/role_skills/community_discovery": typeof autopilot_role_skills_community_discovery;
  "autopilot/role_skills/cto": typeof autopilot_role_skills_cto;
  "autopilot/role_skills/growth/content_enricher": typeof autopilot_role_skills_growth_content_enricher;
  "autopilot/role_skills/growth/content_generation": typeof autopilot_role_skills_growth_content_generation;
  "autopilot/role_skills/growth/content_storage": typeof autopilot_role_skills_growth_content_storage;
  "autopilot/role_skills/growth/discovery": typeof autopilot_role_skills_growth_discovery;
  "autopilot/role_skills/growth/drafts/producer": typeof autopilot_role_skills_growth_drafts_producer;
  "autopilot/role_skills/growth/gap_assessment": typeof autopilot_role_skills_growth_gap_assessment;
  "autopilot/role_skills/growth/market_research": typeof autopilot_role_skills_growth_market_research;
  "autopilot/role_skills/growth/product_context": typeof autopilot_role_skills_growth_product_context;
  "autopilot/role_skills/growth/query_builder": typeof autopilot_role_skills_growth_query_builder;
  "autopilot/role_skills/growth/relevance_scorer": typeof autopilot_role_skills_growth_relevance_scorer;
  "autopilot/role_skills/growth/research_helpers": typeof autopilot_role_skills_growth_research_helpers;
  "autopilot/role_skills/models": typeof autopilot_role_skills_models;
  "autopilot/role_skills/pm/analysis": typeof autopilot_role_skills_pm_analysis;
  "autopilot/role_skills/pm/initiatives": typeof autopilot_role_skills_pm_initiatives;
  "autopilot/role_skills/pm/queries": typeof autopilot_role_skills_pm_queries;
  "autopilot/role_skills/prompts": typeof autopilot_role_skills_prompts;
  "autopilot/role_skills/sales_discovery": typeof autopilot_role_skills_sales_discovery;
  "autopilot/role_skills/sales_mutations": typeof autopilot_role_skills_sales_mutations;
  "autopilot/role_skills/sales_prospecting": typeof autopilot_role_skills_sales_prospecting;
  "autopilot/role_skills/sales_queries": typeof autopilot_role_skills_sales_queries;
  "autopilot/role_skills/shared_exa": typeof autopilot_role_skills_shared_exa;
  "autopilot/role_skills/shared_generation": typeof autopilot_role_skills_shared_generation;
  "autopilot/role_skills/shared_search": typeof autopilot_role_skills_shared_search;
  "autopilot/role_skills/shared_web": typeof autopilot_role_skills_shared_web;
  "autopilot/role_skills/support": typeof autopilot_role_skills_support;
  "autopilot/role_skills/validation/community_posts": typeof autopilot_role_skills_validation_community_posts;
  "autopilot/role_skills/validator": typeof autopilot_role_skills_validator;
  "autopilot/role_skills/validator_prompts": typeof autopilot_role_skills_validator_prompts;
  "autopilot/runtime/executor": typeof autopilot_runtime_executor;
  "autopilot/runtime/lifecycle": typeof autopilot_runtime_lifecycle;
  "autopilot/runtime/mutations": typeof autopilot_runtime_mutations;
  "autopilot/runtime/policy": typeof autopilot_runtime_policy;
  "autopilot/runtime/queries": typeof autopilot_runtime_queries;
  "autopilot/runtime/state": typeof autopilot_runtime_state;
  "autopilot/runtime/view": typeof autopilot_runtime_view;
  "autopilot/sales_mutations": typeof autopilot_sales_mutations;
  "autopilot/schedule/build": typeof autopilot_schedule_build;
  "autopilot/schedule/signals": typeof autopilot_schedule_signals;
  "autopilot/schedule/types": typeof autopilot_schedule_types;
  "autopilot/schema/index": typeof autopilot_schema_index;
  "autopilot/schema/validators": typeof autopilot_schema_validators;
  "autopilot/self_heal": typeof autopilot_self_heal;
  "autopilot/task_mutations": typeof autopilot_task_mutations;
  "autopilot/task_queries": typeof autopilot_task_queries;
  "billing/actions": typeof billing_actions;
  "billing/effective_tier": typeof billing_effective_tier;
  "billing/internal": typeof billing_internal;
  "billing/lib": typeof billing_lib;
  "billing/queries": typeof billing_queries;
  "billing/stripe": typeof billing_stripe;
  "billing/tableFields": typeof billing_tableFields;
  "billing/utils": typeof billing_utils;
  "changelog/ai_actions": typeof changelog_ai_actions;
  "changelog/ai_matching": typeof changelog_ai_matching;
  "changelog/ai_matching_helpers": typeof changelog_ai_matching_helpers;
  "changelog/feedback_linking": typeof changelog_feedback_linking;
  "changelog/lib/action_helpers": typeof changelog_lib_action_helpers;
  "changelog/lib/ai_helpers": typeof changelog_lib_ai_helpers;
  "changelog/lib/commit_grouping": typeof changelog_lib_commit_grouping;
  "changelog/lib/github_fetch": typeof changelog_lib_github_fetch;
  "changelog/mutations": typeof changelog_mutations;
  "changelog/notifications": typeof changelog_notifications;
  "changelog/notifications_helpers": typeof changelog_notifications_helpers;
  "changelog/queries": typeof changelog_queries;
  "changelog/release_commits": typeof changelog_release_commits;
  "changelog/release_lifecycle": typeof changelog_release_lifecycle;
  "changelog/release_notes_ai": typeof changelog_release_notes_ai;
  "changelog/release_versions": typeof changelog_release_versions;
  "changelog/releases": typeof changelog_releases;
  "changelog/releases_internal": typeof changelog_releases_internal;
  "changelog/retroactive": typeof changelog_retroactive;
  "changelog/retroactive_actions": typeof changelog_retroactive_actions;
  "changelog/retroactive_mutations": typeof changelog_retroactive_mutations;
  "changelog/rss": typeof changelog_rss;
  "changelog/scheduling": typeof changelog_scheduling;
  "changelog/subscriptions": typeof changelog_subscriptions;
  "changelog/tableFields": typeof changelog_tableFields;
  crons: typeof crons;
  "domains/actions": typeof domains_actions;
  "domains/crons": typeof domains_crons;
  "domains/internal": typeof domains_internal;
  "domains/publicMutations": typeof domains_publicMutations;
  "domains/queries": typeof domains_queries;
  "domains/vercel": typeof domains_vercel;
  "duplicates/detection": typeof duplicates_detection;
  "duplicates/merge": typeof duplicates_merge;
  "duplicates/queries": typeof duplicates_queries;
  "duplicates/tableFields": typeof duplicates_tableFields;
  "email/analytics": typeof email_analytics;
  "email/health": typeof email_health;
  "email/renderer": typeof email_renderer;
  "email/send": typeof email_send;
  "email/suppression": typeof email_suppression;
  "email/tableFields": typeof email_tableFields;
  "feedback/actions": typeof feedback_actions;
  "feedback/actions_manage": typeof feedback_actions_manage;
  "feedback/api_admin": typeof feedback_api_admin;
  "feedback/api_auth": typeof feedback_api_auth;
  "feedback/api_keys": typeof feedback_api_keys;
  "feedback/api_public_mutations": typeof feedback_api_public_mutations;
  "feedback/api_public_queries": typeof feedback_api_public_queries;
  "feedback/api_public_reads": typeof feedback_api_public_reads;
  "feedback/auto_tagging_actions": typeof feedback_auto_tagging_actions;
  "feedback/auto_tagging_mutations": typeof feedback_auto_tagging_mutations;
  "feedback/auto_tagging_queries": typeof feedback_auto_tagging_queries;
  "feedback/clarification": typeof feedback_clarification;
  "feedback/clarification_difficulty": typeof feedback_clarification_difficulty;
  "feedback/clarification_draft_reply": typeof feedback_clarification_draft_reply;
  "feedback/cleanup": typeof feedback_cleanup;
  "feedback/comments": typeof feedback_comments;
  "feedback/feature_check": typeof feedback_feature_check;
  "feedback/feature_check_action": typeof feedback_feature_check_action;
  "feedback/importance": typeof feedback_importance;
  "feedback/list": typeof feedback_list;
  "feedback/mutations": typeof feedback_mutations;
  "feedback/queries": typeof feedback_queries;
  "feedback/roadmap": typeof feedback_roadmap;
  "feedback/screenshots": typeof feedback_screenshots;
  "feedback/stale": typeof feedback_stale;
  "feedback/status_utils": typeof feedback_status_utils;
  "feedback/subscriptions": typeof feedback_subscriptions;
  "feedback/tableFields": typeof feedback_tableFields;
  "feedback/tags_mutations": typeof feedback_tags_mutations;
  "feedback/tags_queries": typeof feedback_tags_queries;
  "feedback/trash": typeof feedback_trash;
  "feedback/votes": typeof feedback_votes;
  healthCheck: typeof healthCheck;
  http: typeof http;
  "http/admin_content": typeof http_admin_content;
  "http/admin_content_surveys": typeof http_admin_content_surveys;
  "http/admin_feedback": typeof http_admin_feedback;
  "http/admin_management": typeof http_admin_management;
  "http/ai_api": typeof http_ai_api;
  "http/bridge_api": typeof http_bridge_api;
  "http/github_api": typeof http_github_api;
  "http/github_api_helpers": typeof http_github_api_helpers;
  "http/github_api_reads": typeof http_github_api_reads;
  "http/github_webhook": typeof http_github_webhook;
  "http/helpers": typeof http_helpers;
  "http/lib/api_auth": typeof http_lib_api_auth;
  "http/lib/api_helpers": typeof http_lib_api_helpers;
  "http/public_api": typeof http_public_api;
  "http/public_api_feedback_reads": typeof http_public_api_feedback_reads;
  "http/public_api_feedback_writes": typeof http_public_api_feedback_writes;
  "http/public_api_surveys": typeof http_public_api_surveys;
  "integrations/github/actions_node": typeof integrations_github_actions_node;
  "integrations/github/client_actions": typeof integrations_github_client_actions;
  "integrations/github/code_search": typeof integrations_github_code_search;
  "integrations/github/connection_actions": typeof integrations_github_connection_actions;
  "integrations/github/connection_mutations": typeof integrations_github_connection_mutations;
  "integrations/github/exploration_tools": typeof integrations_github_exploration_tools;
  "integrations/github/fetch_actions": typeof integrations_github_fetch_actions;
  "integrations/github/github_helpers": typeof integrations_github_github_helpers;
  "integrations/github/installation_mutations": typeof integrations_github_installation_mutations;
  "integrations/github/issue_imports": typeof integrations_github_issue_imports;
  "integrations/github/issue_mutations": typeof integrations_github_issue_mutations;
  "integrations/github/issue_queries": typeof integrations_github_issue_queries;
  "integrations/github/node_actions": typeof integrations_github_node_actions;
  "integrations/github/product_exploration": typeof integrations_github_product_exploration;
  "integrations/github/product_exploration_helpers": typeof integrations_github_product_exploration_helpers;
  "integrations/github/project_setup_actions": typeof integrations_github_project_setup_actions;
  "integrations/github/project_setup_mutations": typeof integrations_github_project_setup_mutations;
  "integrations/github/project_setup_queries": typeof integrations_github_project_setup_queries;
  "integrations/github/project_setup_shared": typeof integrations_github_project_setup_shared;
  "integrations/github/queries": typeof integrations_github_queries;
  "integrations/github/release_actions": typeof integrations_github_release_actions;
  "integrations/github/repo_analysis": typeof integrations_github_repo_analysis;
  "integrations/github/sync": typeof integrations_github_sync;
  "integrations/github/sync_mutations": typeof integrations_github_sync_mutations;
  "integrations/github/tableFields": typeof integrations_github_tableFields;
  "integrations/github/webhook_issue_processors": typeof integrations_github_webhook_issue_processors;
  "integrations/github/webhook_release_processors": typeof integrations_github_webhook_release_processors;
  "integrations/website_references": typeof integrations_website_references;
  "mcp/handler": typeof mcp_handler;
  "mcp/protocol": typeof mcp_protocol;
  "mcp/tools": typeof mcp_tools;
  "mcp/tools_comments": typeof mcp_tools_comments;
  "mcp/tools_feedback": typeof mcp_tools_feedback;
  "mcp/tools_milestones": typeof mcp_tools_milestones;
  "mcp/tools_organization": typeof mcp_tools_organization;
  "mcp/tools_releases": typeof mcp_tools_releases;
  "mcp/tools_shared": typeof mcp_tools_shared;
  "mcp/tools_tags": typeof mcp_tools_tags;
  "migrations/cleanup_board_fields": typeof migrations_cleanup_board_fields;
  "notifications/preferences": typeof notifications_preferences;
  "notifications/push": typeof notifications_push;
  "notifications/push_queries": typeof notifications_push_queries;
  "notifications/queries": typeof notifications_queries;
  "notifications/shipped": typeof notifications_shipped;
  "notifications/shipped_helpers": typeof notifications_shipped_helpers;
  "notifications/tableFields": typeof notifications_tableFields;
  "notifications/weekly_digest": typeof notifications_weekly_digest;
  "notifications/weekly_digest_helpers": typeof notifications_weekly_digest_helpers;
  "organizations/actions": typeof organizations_actions;
  "organizations/invitation_queries": typeof organizations_invitation_queries;
  "organizations/invitations": typeof organizations_invitations;
  "organizations/members": typeof organizations_members;
  "organizations/milestones_mutations": typeof organizations_milestones_mutations;
  "organizations/milestones_queries": typeof organizations_milestones_queries;
  "organizations/mutations": typeof organizations_mutations;
  "organizations/onboarding": typeof organizations_onboarding;
  "organizations/queries": typeof organizations_queries;
  "organizations/statuses": typeof organizations_statuses;
  "organizations/statuses_queries": typeof organizations_statuses_queries;
  "organizations/super_admin_analytics": typeof organizations_super_admin_analytics;
  "organizations/super_admin_queries": typeof organizations_super_admin_queries;
  "organizations/tableFields": typeof organizations_tableFields;
  "organizations/tag_manager": typeof organizations_tag_manager;
  "organizations/tag_manager_actions": typeof organizations_tag_manager_actions;
  privateData: typeof privateData;
  "shared/access": typeof shared_access;
  "shared/constants": typeof shared_constants;
  "shared/env": typeof shared_env;
  "shared/slug": typeof shared_slug;
  "shared/text_formatters": typeof shared_text_formatters;
  "shared/utils": typeof shared_utils;
  "shared/validators": typeof shared_validators;
  sitemap_public: typeof sitemap_public;
  "status/healthCheck": typeof status_healthCheck;
  "status/incidents": typeof status_incidents;
  "status/monitors": typeof status_monitors;
  "status/publicQueries": typeof status_publicQueries;
  "status/subscriptions": typeof status_subscriptions;
  "status/tableFields": typeof status_tableFields;
  storage: typeof storage;
  "support/conversation_mutations": typeof support_conversation_mutations;
  "support/conversation_queries": typeof support_conversation_queries;
  "support/message_mutations": typeof support_message_mutations;
  "support/message_queries": typeof support_message_queries;
  "support/tableFields": typeof support_tableFields;
  "surveys/lib/analytics_helpers": typeof surveys_lib_analytics_helpers;
  "surveys/mutations": typeof surveys_mutations;
  "surveys/queries": typeof surveys_queries;
  "surveys/questions": typeof surveys_questions;
  "surveys/responses": typeof surveys_responses;
  "surveys/tableFields": typeof surveys_tableFields;
  todos: typeof todos;
  "widget/admin_mutations": typeof widget_admin_mutations;
  "widget/admin_queries": typeof widget_admin_queries;
  "widget/public": typeof widget_public;
  "widget/tableFields": typeof widget_tableFields;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("@convex-dev/better-auth/_generated/component.js").ComponentApi<"betterAuth">;
  aiRuntime: import("@convex-dev/agent/_generated/component.js").ComponentApi<"aiRuntime">;
  stripe: import("@convex-dev/stripe/_generated/component.js").ComponentApi<"stripe">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
  shardedCounter: import("@convex-dev/sharded-counter/_generated/component.js").ComponentApi<"shardedCounter">;
};
